// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Build script for ssh-stamp-bl616-boards.
//!
//! Reads `boards/*.toml` (one file per board, containing pin mappings and an
//! optional documentation URL) and generates `OUT_DIR/boards_gen.rs` with:
//!
//! - A `pub struct` + `impl Board` per board.
//! - The `UART_RX` and `UART_TX` constants of the selected board, taken from
//!   the TOML files, which are the single source of truth.
//! - The `select_board!` macro that expands to the `type B = ...` alias, so
//!   the binary has zero per-board lines.
//!
//! It also writes `OUT_DIR/board_catalog.md`, the pin table that `src/lib.rs`
//! includes into this crate's front page. Every platform's BSP crate
//! generates its own, so the table always sits with the boards it describes.
//!
//! Unlike the Espressif BSP there are no GPIO singletons to hand out: on this
//! part the pins are plain numbers that the port passes to `bflb_gpio_uart_init`
//! at open time, so what is generated here is constants rather than a macro
//! that names peripheral fields.
//!
//! Adding a board = add a `boards/{name}.toml` file + a `board-{name}` feature
//! in `Cargo.toml`. No `.rs` file, no macro editing.

use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

/// Header prepended to every generated file.
const HEADER: &str = "// Auto-generated by build.rs from boards/*.toml — DO NOT EDIT.\n\n";

/// The pin constants of one board, guarded by its feature.
const PINS_BLOCK: &str = r#"/// The GPIO carrying UART0's receive line on this board.
///
/// From `boards/{name}.toml` by way of `build.rs`, not written by hand.
#[cfg(feature = "{feature}")]
pub const UART_RX: u8 = {rx};

/// The GPIO carrying UART0's transmit line on this board.
#[cfg(feature = "{feature}")]
pub const UART_TX: u8 = {tx};

"#;

/// What a build with no board selected gets instead of missing constants.
const NO_BOARD: &str = r#"#[cfg(not(any({features})))]
compile_error!("No board feature selected. Pass --features board-<name>. See the ssh-stamp-bl616-boards crate for available boards.");
"#;

/// Doc-comment + signature for `select_board!`. Per-board `#[cfg]` aliases
/// are inserted at `{arms}` and the fallback feature list at `{features}`.
const SELECT_BOARD_TMPL: &str = r#"/// Select the active board type `B` at compile time.
///
/// Emits a `type B = ...` alias for the active board's struct. The caller can
/// then use `B::NAME` for logging. Zero per-board lines in the binary.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! select_board {
    () => {
{arms}        #[cfg(not(any({features})))]
        compile_error!("No board feature selected.");
    };
}
"#;

/// One `#[cfg]`-guarded `type B` alias inside `select_board!`.
const SELECT_BOARD_ARM: &str = r#"        #[cfg(feature = "{feature}")]
        type B = $crate::{struct_name};
"#;

/// Prose around the generated pin table.
const CATALOG_TMPL: &str = r"# Board catalog

Pin allocation for every board of this platform, generated from its
`boards/*.toml` files on each `cargo doc` (`cargo xtask <board> doc`) run. The
TOML files are the single source of truth: this table is the only place the
allocation is written down, and no README, guide or hand-written doc page
repeats it.

{table}
Cells are GPIO numbers. The port routes them to UART0 when it opens the port,
so changing the TOML changes the firmware — the vendor SDK only muxes UART0
as part of putting its console there, which a build with the console on USB
never does.

Select a board with `cargo xtask <board> build`, or with
`--features board-<board>` when driving cargo directly.
";

/// The table's fixed part: header row plus alignment row.
const CATALOG_HEADER: &str = "\
| Board | Chip | UART RX | UART TX |
|---|---|---|---|
";

/// The parts of a board definition TOML this script reads.
#[derive(Debug, Deserialize)]
struct BoardDef {
    url: Option<String>,
    pins: Pins,
    build: Option<BuildSection>,
}

#[derive(Debug, Deserialize)]
struct Pins {
    uart_rx: u8,
    uart_tx: u8,
}

/// The `[build]` section belongs to `cargo xtask`; the catalog reads the chip
/// name out of it so the table can say which MCU each board carries.
#[derive(Debug, Deserialize)]
struct BuildSection {
    chip: Option<String>,
}

/// A parsed board ready for codegen.
struct Board {
    name: String,
    struct_name: String,
    feature: String,
    url: Option<String>,
    chip: Option<String>,
    uart_rx: u8,
    uart_tx: u8,
}

/// Errors surfaced by the build script as `Result`.
#[derive(Debug)]
enum BuildError {
    /// A board feature was selected in Cargo.toml but no matching TOML file
    /// was found in `boards/`.
    MissingBoardDef { feature: String },
    /// A `boards/*.toml` file could not be read or parsed.
    BoardFile {
        path: PathBuf,
        source: Box<dyn std::error::Error>,
    },
}

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingBoardDef { feature } => write!(
                f,
                "Feature `{feature}` is enabled in Cargo.toml but no corresponding \
                 board definition file `boards/{feature}.toml` was found. \
                 Create it with a [pins] section containing uart_rx and uart_tx.",
            ),
            Self::BoardFile { path, source } => {
                write!(
                    f,
                    "Failed to process board file {}: {source}",
                    path.display()
                )
            }
        }
    }
}

impl std::error::Error for BuildError {}

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

fn main() -> Result<()> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let boards_dir = manifest_dir.join("boards");

    println!("cargo:rerun-if-changed=boards/");

    let boards = load_boards(&boards_dir)?;

    validate_features(&boards)?;

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set by cargo")?);
    fs::write(out_dir.join("boards_gen.rs"), generate_code(&boards)?)?;
    fs::write(out_dir.join("board_catalog.md"), generate_catalog(&boards)?)?;

    Ok(())
}

/// Read all `boards/*.toml` files and parse them into `Board` structs.
fn load_boards(boards_dir: &Path) -> Result<Vec<Board>> {
    if !boards_dir.is_dir() {
        return Ok(Vec::new());
    }

    let mut entries: Vec<_> = fs::read_dir(boards_dir)?
        .filter_map(std::result::Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    entries.sort();

    let mut boards = Vec::new();
    for path in entries {
        let stem = path
            .file_stem()
            .ok_or("board file has no stem")?
            .to_string_lossy()
            .to_string();

        let content = fs::read_to_string(&path).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        let def: BoardDef = toml::from_str(&content).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        boards.push(Board {
            name: stem.clone(),
            struct_name: to_pascal_case(&stem),
            feature: format!("board-{stem}"),
            url: def.url,
            chip: def.build.and_then(|b| b.chip),
            uart_rx: def.pins.uart_rx,
            uart_tx: def.pins.uart_tx,
        });
    }

    Ok(boards)
}

/// Check that every selected `CARGO_FEATURE_BOARD_*` env var has a matching
/// board TOML file.
fn validate_features(boards: &[Board]) -> Result<()> {
    for (key, _val) in std::env::vars() {
        if let Some(rest) = key.strip_prefix("CARGO_FEATURE_BOARD_") {
            let requested = format!("board-{}", rest.to_lowercase().replace('_', "-"));
            if boards.iter().any(|b| b.feature == requested) {
                continue;
            }
            return Err(BuildError::MissingBoardDef { feature: requested }.into());
        }
    }
    Ok(())
}

/// Convert `sipeed-m0s-dock` -> `SipeedM0sDock`.
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn generate_code(boards: &[Board]) -> Result<String> {
    let mut out = String::new();

    out.push_str(HEADER);
    gen_structs(&mut out, boards)?;
    gen_pins(&mut out, boards);
    gen_select_board(&mut out, boards);

    Ok(out)
}

fn gen_structs(out: &mut String, boards: &[Board]) -> Result<()> {
    // One `pub struct` + `impl Board` per board, with a rustdoc link to the
    // board's official documentation page (if the TOML provided a `url`).
    for b in boards {
        let doc = match &b.url {
            Some(url) => format!("/// Board: {}.\n///\n/// <{url}>", b.name),
            None => format!("/// Board: {}.", b.name),
        };
        writeln!(
            out,
            "{doc}\npub struct {s};\nimpl Board for {s} {{\n    const NAME: &str = \"{n}\";\n}}",
            s = b.struct_name,
            n = b.name,
        )?;
        out.push('\n');
    }
    Ok(())
}

/// The selected board's pin numbers, as constants.
///
/// Constants rather than a macro: on this part a pin is a plain number that
/// the port hands to `bflb_gpio_uart_init` when it opens UART0, not a
/// peripheral singleton that has to be named at the call site.
fn gen_pins(out: &mut String, boards: &[Board]) {
    for b in boards {
        out.push_str(
            &PINS_BLOCK
                .replace("{name}", &b.name)
                .replace("{feature}", &b.feature)
                .replace("{rx}", &b.uart_rx.to_string())
                .replace("{tx}", &b.uart_tx.to_string()),
        );
    }

    // The fallback `not(any(...))` guard names the real problem, rather than
    // leaving every use of the constants to report them as missing.
    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    out.push_str(&NO_BOARD.replace("{features}", &features.join(", ")));
    out.push('\n');
}

fn gen_select_board(out: &mut String, boards: &[Board]) {
    // Build the per-board `type B = ...` aliases. Each is guarded by its
    // `#[cfg(feature = ...)]` so only the active board's alias is compiled.
    let mut arms = String::new();
    for b in boards {
        arms.push_str(
            &SELECT_BOARD_ARM
                .replace("{feature}", &b.feature)
                .replace("{struct_name}", &b.struct_name),
        );
    }

    // The fallback `not(any(...))` guard produces a compile_error if no board
    // feature is selected.
    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = SELECT_BOARD_TMPL
        .replace("{arms}", &arms)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
}

/// Render the board catalog as a Markdown page.
fn generate_catalog(boards: &[Board]) -> Result<String> {
    let mut table = String::from(CATALOG_HEADER);
    for b in boards {
        // The board name doubles as the link to the vendor's board page, so
        // the table stays narrow enough to read without a URL column.
        let name = match &b.url {
            Some(url) => format!("[`{}`]({url})", b.name),
            None => format!("`{}`", b.name),
        };
        writeln!(
            table,
            "| {name} | {chip} | {} | {} |",
            b.uart_rx,
            b.uart_tx,
            chip = b.chip.as_deref().unwrap_or("x"),
        )?;
    }

    Ok(CATALOG_TMPL.replace("{table}", &table))
}
