// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Emitters, one per generated artifact.
//!
//! A BSP build script calls these in order, appending to one `String` that
//! ends up as `OUT_DIR/boards_gen.rs`.

mod catalog;
mod macro_shell;
mod pins;
mod select_board;
mod structs;

pub use catalog::{Column, catalog};
pub use macro_shell::{MacroShell, macro_shell};
pub use pins::{PinField, Pins, pin_macro, uart_pins};
pub use select_board::select_board;
pub use structs::{board_trait, structs};

/// The "do not edit" banner every generated file starts with.
const HEADER: &str = "// Auto-generated by build.rs from boards/*.toml — DO NOT EDIT.\n\n";

/// Emit the generated-file banner.
pub fn header(out: &mut String) {
    out.push_str(HEADER);
}
