// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! `take_*_pins!` macros, described as data.
//!
//! UART, CAN and Ethernet pin macros are the same algorithm with different
//! tuple shapes, so there is one emitter and each macro is expressed as a
//! closure returning the tuple (or the reason it cannot be built).

use std::fmt::Write as _;

use crate::Target;
use crate::emit::macro_shell::{MacroShell, macro_shell};
use crate::load::Board;
use crate::render::render;

/// One element of a pin macro's returned tuple.
pub enum PinField {
    /// A peripheral singleton, spelled by [`Target::pin_token`].
    Pin(u8),
    /// The bare pin number as a `u8` literal, for code that persists it.
    Number(u8),
}

/// A board's pin tuple, or the `compile_error!` message explaining why this
/// board cannot supply one.
pub type Pins = std::result::Result<Vec<PinField>, String>;

const TUPLE_BRANCH: &str = r"        {{
            (
{fields}            )
        }}
";

const MISSING_BRANCH: &str = r#"        {{
            compile_error!("{message}");
        }}
"#;

/// Emit a `take_*_pins!` macro: one `#[cfg]` branch per board holding a
/// tuple of pin tokens, or a `compile_error!` for boards lacking the
/// peripheral.
pub fn pin_macro<E>(
    out: &mut String,
    target: &Target,
    shell: &MacroShell<'_>,
    boards: &[Board<E>],
    fields: impl Fn(&Board<E>) -> Pins,
) {
    macro_shell(out, target, shell, boards, |board| match fields(board) {
        Ok(tuple) => {
            let mut lines = String::new();
            for field in &tuple {
                let _ = writeln!(lines, "                {},", token(field, target));
            }
            Some(render(TUPLE_BRANCH, &[("fields", &lines)]))
        }
        Err(message) => Some(render(MISSING_BRANCH, &[("message", &message)])),
    });
}

fn token(field: &PinField, target: &Target) -> String {
    match *field {
        PinField::Pin(n) => (target.pin_token)(n),
        PinField::Number(n) => format!("{n}u8"),
    }
}

const UART_DOC: &str = r"/// Extract UART GPIO pins and logical pin numbers from `peripherals`.
///
/// Returns `(rx_pin, tx_pin, rx_num, tx_num)`. The pin numbers come from
/// `boards/*.toml` — this macro is generated by `build.rs`, not hand-written.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
";

/// Emit `take_uart_pins!`, the one pin macro every target has — `[pins]`
/// with `uart_rx`/`uart_tx` is part of the common board schema.
pub fn uart_pins<E>(out: &mut String, target: &Target, boards: &[Board<E>]) {
    let shell = MacroShell {
        name: "take_uart_pins",
        doc: UART_DOC,
    };
    pin_macro(out, target, &shell, boards, |board| {
        Ok(vec![
            PinField::Pin(board.uart_rx),
            PinField::Pin(board.uart_tx),
            PinField::Number(board.uart_rx),
            PinField::Number(board.uart_tx),
        ])
    });
}
