# SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "ssh-stamp-hal"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
description = "Hardware Abstraction Layer traits for ssh-stamp"
documentation = "https://docs.rs/ssh-stamp-hal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
embassy-sync = { workspace = true }
embassy-net = { workspace = true }
heapless = { workspace = true }

[features]
default = []
sftp-ota = []

[lints]
workspace = true
