// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Build script for ssh-stamp-esp32-boards.
//!
//! Reads `boards/*.toml` (one file per board, containing pin mappings and an
//! optional documentation URL) and generates `OUT_DIR/boards_gen.rs` with:
//!
//! - A `pub struct` + `impl Board` per board.
//! - The `take_uart_pins!` macro whose `#[cfg]` branches emit the correct
//!   `peripherals.GPIO{N}.into()` tokens — the pin numbers come from the TOML
//!   files, which are the single source of truth.
//! - The `select_board!` macro that expands to the `cfg_if!` + `use` block,
//!   so the binary has zero per-board lines.
//!
//! It also writes `OUT_DIR/board_catalog.md`, the UART/CAN/I2C pin table that
//! `src/lib.rs` includes into this crate's front page. Every platform's BSP
//! crate generates its own, so the table always sits with the boards it
//! describes instead of in a top-level page or a Markdown file under `docs/`.
//!
//! Adding a board = add a `boards/{name}.toml` file + a `board-{name}` feature
//! in `Cargo.toml`. No `.rs` file, no macro editing.

use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

// --- Static code templates (the boilerplate around the per-board data) ---

/// Header prepended to every generated file.
const HEADER: &str = "// Auto-generated by build.rs from boards/*.toml — DO NOT EDIT.\n\n";

/// Doc-comment + signature for `take_uart_pins!`. Per-board branches are
/// inserted at `{branches}` and the fallback `not(any(...))` feature list
/// at `{features}`.
const TAKE_UART_PINS_TMPL: &str = r#"/// Extract UART GPIO pins and logical pin numbers from `peripherals`.
///
/// Returns `(rx_pin, tx_pin, rx_num, tx_num)`. The pin numbers come from
/// `boards/*.toml` — this macro is generated by `build.rs`, not hand-written.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! take_uart_pins {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-esp32-boards crate for available boards.");
        }}
    }};
}
"#;

/// Doc-comment + signature for `select_board!`. Per-board `#[cfg]` aliases
/// are inserted at `{arms}` and the fallback feature list at `{features}`.
/// Each arm creates a `type B = ...` alias guarded by a `#[cfg(feature = ...)]`
/// attribute, so exactly one `B` is in scope at the call site — no `cfg_if!`
/// block scoping issues.
const SELECT_BOARD_TMPL: &str = r#"/// Select the active board type `B` at compile time.
///
/// Emits a `type B = ...` alias for the active board's struct. The caller can
/// then use `B::NAME` for logging. Zero per-board lines in the binary.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! select_board {
    () => {
{arms}        #[cfg(not(any({features})))]
        compile_error!("No board feature selected.");
    };
}
"#;

// --- TOML deserialization structs ---

#[derive(Debug, Deserialize)]
struct BoardDef {
    url: Option<String>,
    pins: Pins,
    can_mux: Option<CanMux>,
    build: Option<BuildSection>,
}

#[derive(Debug, Deserialize)]
struct Pins {
    uart_rx: u8,
    uart_tx: u8,
    can_tx: Option<u8>,
    can_rx: Option<u8>,
    i2c_sda: Option<u8>,
    i2c_scl: Option<u8>,
}

/// The `[build]` section belongs to `cargo xtask`; the catalog reads the
/// chip name out of it so the table can say which MCU each board carries.
#[derive(Debug, Deserialize)]
struct BuildSection {
    chip: Option<String>,
}

/// Boards that share their CAN pins with other functions behind an
/// I2C-controlled mux (e.g. an IO expander driving an analog switch)
/// declare the routing here: the I2C pins and the `[address, value]`
/// register writes that select the CAN transceiver.
#[derive(Debug, Deserialize)]
struct CanMux {
    i2c_sda: u8,
    i2c_scl: u8,
    writes: Vec<[u8; 2]>,
}

/// A parsed board ready for codegen.
struct Board {
    name: String,
    struct_name: String,
    feature: String,
    url: Option<String>,
    chip: Option<String>,
    uart_rx: u8,
    uart_tx: u8,
    can_tx: Option<u8>,
    can_rx: Option<u8>,
    i2c_sda: Option<u8>,
    i2c_scl: Option<u8>,
    can_mux: Option<CanMux>,
}

/// Errors surfaced by the build script as `Result`.
#[derive(Debug)]
enum BuildError {
    /// A board feature was selected in Cargo.toml but no matching TOML file
    /// was found in `boards/`.
    MissingBoardDef { feature: String },
    /// A `boards/*.toml` file could not be read or parsed.
    BoardFile {
        path: PathBuf,
        source: Box<dyn std::error::Error>,
    },
}

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingBoardDef { feature } => write!(
                f,
                "Feature `{feature}` is enabled in Cargo.toml but no corresponding \
                 board definition file `boards/{feature}.toml` was found. \
                 Create it with a [pins] section containing uart_rx and uart_tx.",
            ),
            Self::BoardFile { path, source } => {
                write!(
                    f,
                    "Failed to process board file {}: {source}",
                    path.display()
                )
            }
        }
    }
}

impl std::error::Error for BuildError {}

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

fn main() -> Result<()> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let boards_dir = manifest_dir.join("boards");

    println!("cargo:rerun-if-changed=boards/");

    let boards = load_boards(&boards_dir)?;

    validate_features(&boards)?;

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set by cargo")?);
    fs::write(out_dir.join("boards_gen.rs"), generate_code(&boards)?)?;
    fs::write(out_dir.join("board_catalog.md"), generate_catalog(&boards)?)?;

    Ok(())
}

/// Read all `boards/*.toml` files and parse them into `Board` structs.
fn load_boards(boards_dir: &Path) -> Result<Vec<Board>> {
    if !boards_dir.is_dir() {
        return Ok(Vec::new());
    }

    let mut entries: Vec<_> = fs::read_dir(boards_dir)?
        .filter_map(std::result::Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    entries.sort();

    let mut boards = Vec::new();
    for path in entries {
        let stem = path
            .file_stem()
            .ok_or("board file has no stem")?
            .to_string_lossy()
            .to_string();

        let content = fs::read_to_string(&path).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        let def: BoardDef = toml::from_str(&content).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        boards.push(Board {
            name: stem.clone(),
            struct_name: to_pascal_case(&stem),
            feature: format!("board-{stem}"),
            url: def.url,
            chip: def.build.and_then(|b| b.chip),
            uart_rx: def.pins.uart_rx,
            uart_tx: def.pins.uart_tx,
            can_tx: def.pins.can_tx,
            can_rx: def.pins.can_rx,
            i2c_sda: def.pins.i2c_sda,
            i2c_scl: def.pins.i2c_scl,
            can_mux: def.can_mux,
        });
    }

    Ok(boards)
}

/// Check that every selected `CARGO_FEATURE_BOARD_*` env var has a matching
/// board TOML file.
fn validate_features(boards: &[Board]) -> Result<()> {
    for (key, _val) in std::env::vars() {
        if let Some(rest) = key.strip_prefix("CARGO_FEATURE_BOARD_") {
            let requested = format!("board-{}", rest.to_lowercase().replace('_', "-"));
            if boards.iter().any(|b| b.feature == requested) {
                continue;
            }
            return Err(BuildError::MissingBoardDef { feature: requested }.into());
        }
    }
    Ok(())
}

/// Convert `esp32c6-devkitc` -> `Esp32c6Devkitc`.
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn generate_code(boards: &[Board]) -> Result<String> {
    let mut out = String::new();

    out.push_str(HEADER);
    gen_structs(&mut out, boards)?;
    gen_take_uart_pins(&mut out, boards);
    gen_take_can_pins(&mut out, boards);
    gen_setup_can_transceiver(&mut out, boards);
    gen_select_board(&mut out, boards);

    Ok(out)
}

fn gen_structs(out: &mut String, boards: &[Board]) -> Result<()> {
    // One `pub struct` + `impl Board` per board, with a rustdoc link to the
    // board's official documentation page (if the TOML provided a `url`).
    for b in boards {
        let doc = match &b.url {
            Some(url) => format!("/// Board: {}.\n///\n/// <{url}>", b.name),
            None => format!("/// Board: {}.", b.name),
        };
        writeln!(
            out,
            "{doc}\npub struct {s};\nimpl Board for {s} {{\n    const NAME: &str = \"{n}\";\n}}",
            s = b.struct_name,
            n = b.name,
        )?;
        out.push('\n');
    }
    Ok(())
}

/// Prose around the generated pin table. `{table}` receives the rows,
/// `{mux_note}` a sentence that is only relevant when some board on this
/// platform muxes its pins.
const CATALOG_TMPL: &str = r"# Board catalog

Pin allocation for every board of this platform, generated from its
`boards/*.toml` files on each `cargo doc` (`cargo xtask doc`) run. The TOML
files are the single source of truth: this table is the only place the
allocation is written down, and no README, guide or hand-written doc page
repeats it.

{table}
Cells are GPIO numbers. `x` marks a bus that is neither supported nor tested
on that board yet — either the hardware does not break it out, or nothing has
driven it there so far. Adding the pins to the board's TOML is what fills the
cell in, here and in the firmware.
{mux_note}
Select a board with `cargo xtask build <board>`, or with
`--features board-<board>` when driving cargo directly.
";

/// Appended to the catalog when at least one board has a `[can_mux]`.
const CATALOG_MUX_NOTE: &str = "
Pins marked `(mux)` are not a bus of their own: the firmware drives them to
steer an on-board switch or IO expander (the `[can_mux]` section of the
board's TOML) before it can use the bus they route.
";

/// The table's fixed part: header row plus alignment row.
const CATALOG_HEADER: &str = "\
| Board | Chip | UART RX | UART TX | CAN TX | CAN RX | I2C SDA | I2C SCL |
|---|---|---|---|---|---|---|---|
";

/// A GPIO cell: the number, or `x` when the board has no such pin.
fn pin_cell(pin: Option<u8>) -> String {
    pin.map_or_else(|| "x".to_string(), |n| n.to_string())
}

/// An I2C cell. A board can expose I2C pins in `[pins]`, or carry them only
/// as the control bus of a `[can_mux]`; the two are worth telling apart.
fn i2c_cell(pin: Option<u8>, mux_pin: Option<u8>) -> String {
    match (pin, mux_pin) {
        (Some(n), _) => n.to_string(),
        (None, Some(n)) => format!("{n} (mux)"),
        (None, None) => "x".to_string(),
    }
}

/// Render the board catalog as a Markdown page.
///
/// Included verbatim into the crate documentation by `src/lib.rs`, which puts
/// the table on this platform's front page rather than in a module of its own
/// or in a Markdown file under `docs/`.
fn generate_catalog(boards: &[Board]) -> Result<String> {
    let mut table = String::from(CATALOG_HEADER);
    for b in boards {
        // The board name doubles as the link to the vendor's board page, so
        // the table stays narrow enough to read without a URL column.
        let name = match &b.url {
            Some(url) => format!("[`{}`]({url})", b.name),
            None => format!("`{}`", b.name),
        };
        let mux = b.can_mux.as_ref();
        writeln!(
            table,
            "| {name} | {chip} | {} | {} | {} | {} | {} | {} |",
            b.uart_rx,
            b.uart_tx,
            pin_cell(b.can_tx),
            pin_cell(b.can_rx),
            i2c_cell(b.i2c_sda, mux.map(|m| m.i2c_sda)),
            i2c_cell(b.i2c_scl, mux.map(|m| m.i2c_scl)),
            chip = b.chip.as_deref().unwrap_or("x"),
        )?;
    }

    let mux_note = if boards.iter().any(|b| b.can_mux.is_some()) {
        CATALOG_MUX_NOTE
    } else {
        ""
    };

    Ok(CATALOG_TMPL
        .replace("{table}", &table)
        .replace("{mux_note}", mux_note))
}

/// Per-board `#[cfg]` branch inside `take_uart_pins!`.
///
/// Each branch expands to a tuple of `(AnyPin, AnyPin, u8, u8)` — the two GPIO
/// singletons consumed by the UART driver, plus the raw pin numbers persisted
/// in `SSHStampConfig`. The `GPIO{N}` field-access tokens are built here from
/// the TOML's pin numbers; they cannot be constructed at source level because
/// esp-hal's peripheral singletons are named fields (`peripherals.GPIO10`).
const UART_PIN_BRANCH: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            (
                $peripherals.GPIO{rx}.into(),
                $peripherals.GPIO{tx}.into(),
                {rx}u8,
                {tx}u8,
            )
        }}
"#;

fn gen_take_uart_pins(out: &mut String, boards: &[Board]) {
    // Build the per-board `#[cfg]` branches from the TOML pin data.
    let mut branches = String::new();
    for b in boards {
        branches.push_str(
            &UART_PIN_BRANCH
                .replace("{feature}", &b.feature)
                .replace("{rx}", &b.uart_rx.to_string())
                .replace("{tx}", &b.uart_tx.to_string()),
        );
    }

    // The fallback `not(any(...))` guard lists every board feature so that
    // selecting none produces a clear compile_error.
    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = TAKE_UART_PINS_TMPL
        .replace("{branches}", &branches)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
    out.push('\n');
}

/// Doc-comment + signature for `take_can_pins!`. Per-board branches are
/// inserted at `{branches}` and the fallback `not(any(...))` feature list
/// at `{features}`.
const TAKE_CAN_PINS_TMPL: &str = r#"/// Extract CAN GPIO pins from `peripherals`.
///
/// Returns `(tx_pin, rx_pin)`. The pin numbers come from `boards/*.toml`.
/// Only call this macro when the `can` feature is enabled.
///
/// # Panics
///
/// Compile-time error if no board feature is selected, or if the selected
/// board does not have CAN pins defined.
#[macro_export]
macro_rules! take_can_pins {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-esp32-boards crate for available boards.");
        }}
    }};
}
"#;

/// Per-board `#[cfg]` branch inside `take_can_pins!`.
const CAN_PIN_BRANCH_SOME: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            (
                $peripherals.GPIO{tx}.into(),
                $peripherals.GPIO{rx}.into(),
            )
        }}
"#;

const CAN_PIN_BRANCH_NONE: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            compile_error!("Board `{feature}` does not have CAN pins defined. Enable the `can` feature only for boards with CAN support.");
        }}
"#;

fn gen_take_can_pins(out: &mut String, boards: &[Board]) {
    let mut branches = String::new();
    for b in boards {
        if let (Some(tx), Some(rx)) = (b.can_tx, b.can_rx) {
            branches.push_str(
                &CAN_PIN_BRANCH_SOME
                    .replace("{feature}", &b.feature)
                    .replace("{tx}", &tx.to_string())
                    .replace("{rx}", &rx.to_string()),
            );
        } else {
            branches.push_str(&CAN_PIN_BRANCH_NONE.replace("{feature}", &b.feature));
        }
    }

    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = TAKE_CAN_PINS_TMPL
        .replace("{branches}", &branches)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
    out.push('\n');
}

/// Doc-comment + signature for `setup_can_transceiver!`. Per-board branches
/// are inserted at `{branches}` and the fallback `not(any(...))` feature
/// list at `{features}`.
const SETUP_CAN_TRANSCEIVER_TMPL: &str = r#"/// Prepare the board's CAN transceiver routing, if it needs any.
///
/// Boards that share their CAN pins with other functions behind an
/// I2C-controlled mux declare the routing in the `[can_mux]` section of
/// their TOML (I2C pins plus `[address, value]` register writes); this
/// macro performs those writes, consuming the I2C peripheral and mux pins
/// from `peripherals`. Boards without a `[can_mux]` section expand to a
/// no-op. Only call this macro when the `can` feature is enabled.
///
/// # Panics
///
/// Panics if the I2C peripheral cannot be initialised. Compile-time error
/// if no board feature is selected.
#[macro_export]
macro_rules! setup_can_transceiver {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-esp32-boards crate for available boards.");
        }}
    }};
}
"#;

/// `#[cfg]` branch inside `setup_can_transceiver!` for a board with a
/// `[can_mux]` TOML section. The `{writes}` placeholder receives one
/// `CAN_MUX_WRITE` line per `[address, value]` pair.
const CAN_MUX_BRANCH: &str = r#"        #[cfg(feature = "{feature}")]
        {
            let mut i2c = ::esp_hal::i2c::master::I2c::new(
                $peripherals.I2C0,
                ::esp_hal::i2c::master::Config::default(),
            )
            .expect("I2C init error")
            .with_sda($peripherals.GPIO{sda})
            .with_scl($peripherals.GPIO{scl});
{writes}        }
"#;

/// One I2C register write inside a `CAN_MUX_BRANCH`.
const CAN_MUX_WRITE: &str = r#"            if let Err(e) = i2c.write({addr}u8, &[{value}u8]) {
                ::log::warn!("CAN mux I2C write failed: {e:?}");
            }
"#;

fn gen_setup_can_transceiver(out: &mut String, boards: &[Board]) {
    // Branches are only emitted for boards that declare a `[can_mux]`
    // section; for every other board the macro expands to nothing.
    let mut branches = String::new();
    for b in boards {
        let Some(mux) = &b.can_mux else { continue };
        let mut writes = String::new();
        for w in &mux.writes {
            writes.push_str(
                &CAN_MUX_WRITE
                    .replace("{addr}", &format!("{:#04x}", w[0]))
                    .replace("{value}", &format!("{:#04x}", w[1])),
            );
        }
        branches.push_str(
            &CAN_MUX_BRANCH
                .replace("{feature}", &b.feature)
                .replace("{sda}", &mux.i2c_sda.to_string())
                .replace("{scl}", &mux.i2c_scl.to_string())
                .replace("{writes}", &writes),
        );
    }

    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = SETUP_CAN_TRANSCEIVER_TMPL
        .replace("{branches}", &branches)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
    out.push('\n');
}

/// One `#[cfg]`-guarded `type B` alias inside `select_board!`.
const SELECT_BOARD_ARM: &str = r#"        #[cfg(feature = "{feature}")]
        type B = $crate::{struct_name};
"#;

fn gen_select_board(out: &mut String, boards: &[Board]) {
    // Build the per-board `type B = ...` aliases. Each is guarded by its
    // `#[cfg(feature = ...)]` so only the active board's alias is compiled.
    let mut arms = String::new();
    for b in boards {
        arms.push_str(
            &SELECT_BOARD_ARM
                .replace("{feature}", &b.feature)
                .replace("{struct_name}", &b.struct_name),
        );
    }

    // The fallback `not(any(...))` guard produces a compile_error if no board
    // feature is selected.
    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = SELECT_BOARD_TMPL
        .replace("{arms}", &arms)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
}
