// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Build script for ssh-stamp-esp32-boards.
//!
//! Reads `boards/*.toml` (one file per board, containing pin mappings and an
//! optional documentation URL) and generates `OUT_DIR/boards_gen.rs` with:
//!
//! - A `pub struct` + `impl Board` per board.
//! - The `take_uart_pins!` macro whose `#[cfg]` branches emit the correct
//!   `peripherals.GPIO{N}.into()` tokens — the pin numbers come from the TOML
//!   files, which are the single source of truth.
//! - The `select_board!` macro that expands to the `cfg_if!` + `use` block,
//!   so the binary has zero per-board lines.
//! - A rustdoc board-catalog table.
//!
//! Adding a board = add a `boards/{name}.toml` file + a `board-{name}` feature
//! in `Cargo.toml`. No `.rs` file, no macro editing.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

// --- Static code templates (the boilerplate around the per-board data) ---

/// Header prepended to every generated file.
const HEADER: &str = "// Auto-generated by build.rs from boards/*.toml — DO NOT EDIT.\n\n";

/// Doc-comment + signature for `take_uart_pins!`. Per-board branches are
/// inserted at `{branches}` and the fallback `not(any(...))` feature list
/// at `{features}`.
const TAKE_UART_PINS_TMPL: &str = r#"/// Extract UART GPIO pins and logical pin numbers from `peripherals`.
///
/// Returns `(rx_pin, tx_pin, rx_num, tx_num)`. The pin numbers come from
/// `boards/*.toml` — this macro is generated by `build.rs`, not hand-written.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! take_uart_pins {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-esp32-boards crate for available boards.");
        }}
    }};
}
"#;

/// Doc-comment + signature for `select_board!`. Per-board `cfg_if!` arms are
/// inserted at `{arms}`.
const SELECT_BOARD_TMPL: &str = r#"/// Select the active board type `B` at compile time.
///
/// Expands to a `cfg_if!` block that imports the active board's struct as `B`.
/// The caller can then use `B::NAME` for logging. Zero per-board lines in the binary.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! select_board {
    () => {
        cfg_if::cfg_if!(
{arms}            else {
                compile_error!("No board feature selected.");
            }
        );
    };
}
"#;

// --- TOML deserialization structs ---

#[derive(Debug, Deserialize)]
struct BoardDef {
    url: Option<String>,
    pins: Pins,
}

#[derive(Debug, Deserialize)]
struct Pins {
    uart_rx: u8,
    uart_tx: u8,
}

/// A parsed board ready for codegen.
struct Board {
    /// Filename without `.toml` (e.g. `esp32c6-devkitc`).
    name: String,
    /// `PascalCase` struct name (e.g. `Esp32c6Devkitc`).
    struct_name: String,
    /// Cargo feature name (e.g. `board-esp32c6-devkitc`).
    feature: String,
    url: Option<String>,
    uart_rx: u8,
    uart_tx: u8,
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let boards_dir = manifest_dir.join("boards");

    println!("cargo:rerun-if-changed=boards/");

    let mut boards: Vec<Board> = Vec::new();

    if boards_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(&boards_dir)
            .unwrap_or_else(|e| panic!("Failed to read boards/ directory: {e}"))
            .filter_map(std::result::Result::ok)
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
            .collect();
        entries.sort();

        for path in entries {
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();

            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));

            let def: BoardDef = toml::from_str(&content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {e}", path.display()));

            boards.push(Board {
                name: stem.clone(),
                struct_name: to_pascal_case(&stem),
                feature: format!("board-{stem}"),
                url: def.url,
                uart_rx: def.pins.uart_rx,
                uart_tx: def.pins.uart_tx,
            });
        }
    }

    // Validation: if a board feature is selected but no matching TOML was
    // found, fail loudly.
    for (key, _val) in std::env::vars() {
        if let Some(rest) = key.strip_prefix("CARGO_FEATURE_BOARD_") {
            let requested = format!("board-{}", rest.to_lowercase().replace('_', "-"));
            if boards.iter().any(|b| b.feature == requested) {
                continue;
            }
            panic!(
                "Feature `{requested}` is enabled in Cargo.toml but no corresponding \
                 board definition file `boards/{requested}.toml` was found. \
                 Create it with a [pins] section containing uart_rx and uart_tx.",
            );
        }
    }

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("boards_gen.rs");
    fs::write(&out_path, generate_code(&boards))
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_path.display()));
}

/// Convert `esp32c6-devkitc` -> `Esp32c6Devkitc`.
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn generate_code(boards: &[Board]) -> String {
    let mut out = String::new();

    out.push_str(HEADER);
    gen_structs(&mut out, boards);
    gen_catalog(&mut out, boards);
    gen_take_uart_pins(&mut out, boards);
    gen_select_board(&mut out, boards);

    out
}

fn gen_structs(out: &mut String, boards: &[Board]) {
    for b in boards {
        let doc = match &b.url {
            Some(url) => format!("/// Board: {}.\n///\n/// <{url}>", b.name),
            None => format!("/// Board: {}.", b.name),
        };
        writeln!(
            out,
            "{doc}\npub struct {s};\nimpl Board for {s} {{\n    const NAME: &str = \"{n}\";\n}}\n",
            s = b.struct_name,
            n = b.name,
        )
        .unwrap();
    }
}

fn gen_catalog(out: &mut String, boards: &[Board]) {
    let mut table = String::from(
        "/// # Available boards\n\
         ///\n\
         /// | Board feature | UART RX | UART TX | URL |\n\
         /// |---|---|---|---|\n",
    );
    for b in boards {
        let url = match &b.url {
            Some(u) => format!("<{u}>"),
            None => "—".to_string(),
        };
        writeln!(
            table,
            "/// | `{}` | {} | {} | {} |",
            b.feature, b.uart_rx, b.uart_tx, url
        )
        .unwrap();
    }
    table.push_str("pub mod board_catalog {}\n\n");
    out.push_str(&table);
}

fn gen_take_uart_pins(out: &mut String, boards: &[Board]) {
    let mut branches = String::new();
    for b in boards {
        writeln!(
            branches,
            "        #[cfg(feature = \"{f}\")]\n\
             \x20        {{\n\
             \x20            (\n\
             \x20                $peripherals.GPIO{rx}.into(),\n\
             \x20                $peripherals.GPIO{tx}.into(),\n\
             \x20                {rx}u8,\n\
             \x20                {tx}u8,\n\
             \x20            )\n\
             \x20        }}\n",
            f = b.feature,
            rx = b.uart_rx,
            tx = b.uart_tx,
        )
        .unwrap();
    }

    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = TAKE_UART_PINS_TMPL
        .replace("{branches}", &branches)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
    out.push('\n');
}

fn gen_select_board(out: &mut String, boards: &[Board]) {
    let mut arms = String::new();
    for (i, b) in boards.iter().enumerate() {
        let kw = if i == 0 { "if" } else { "else if" };
        writeln!(
            arms,
            "            {kw} #[cfg(feature = \"{f}\")] {{\n\
             \x20                use $crate::{s} as B;\n\
             \x20            }}\n",
            kw = kw,
            f = b.feature,
            s = b.struct_name,
        )
        .unwrap();
    }

    let rendered = SELECT_BOARD_TMPL.replace("{arms}", &arms);
    out.push_str(&rendered);
}
