// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Build script for ssh-stamp-esp32-boards.
//!
//! Reads `boards/*.toml` (one file per board, containing pin mappings and an
//! optional documentation URL) and generates `OUT_DIR/boards_gen.rs` with:
//!
//! - A `pub struct` + `impl Board` per board.
//! - The `take_uart_pins!` macro whose `#[cfg]` branches emit the correct
//!   `peripherals.GPIO{N}.into()` tokens — the pin numbers come from the TOML
//!   files, which are the single source of truth.
//! - The `select_board!` macro that expands to the `cfg_if!` + `use` block,
//!   so the binary has zero per-board lines.
//! - A rustdoc board-catalog table.
//!
//! Adding a board = add a `boards/{name}.toml` file + a `board-{name}` feature
//! in `Cargo.toml`. No `.rs` file, no macro editing.

use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

// --- Static code templates (the boilerplate around the per-board data) ---

/// Header prepended to every generated file.
const HEADER: &str = "// Auto-generated by build.rs from boards/*.toml — DO NOT EDIT.\n\n";

/// Doc-comment + signature for `take_uart_pins!`. Per-board branches are
/// inserted at `{branches}` and the fallback `not(any(...))` feature list
/// at `{features}`.
const TAKE_UART_PINS_TMPL: &str = r#"/// Extract UART GPIO pins and logical pin numbers from `peripherals`.
///
/// Returns `(rx_pin, tx_pin, rx_num, tx_num)`. The pin numbers come from
/// `boards/*.toml` — this macro is generated by `build.rs`, not hand-written.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! take_uart_pins {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-esp32-boards crate for available boards.");
        }}
    }};
}
"#;

/// Doc-comment + signature for `select_board!`. Per-board `#[cfg]` aliases
/// are inserted at `{arms}` and the fallback feature list at `{features}`.
/// Each arm creates a `type B = ...` alias guarded by a `#[cfg(feature = ...)]`
/// attribute, so exactly one `B` is in scope at the call site — no `cfg_if!`
/// block scoping issues.
const SELECT_BOARD_TMPL: &str = r#"/// Select the active board type `B` at compile time.
///
/// Emits a `type B = ...` alias for the active board's struct. The caller can
/// then use `B::NAME` for logging. Zero per-board lines in the binary.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! select_board {
    () => {
{arms}        #[cfg(not(any({features})))]
        compile_error!("No board feature selected.");
    };
}
"#;

// --- TOML deserialization structs ---

#[derive(Debug, Deserialize)]
struct BoardDef {
    url: Option<String>,
    pins: Pins,
}

#[derive(Debug, Deserialize)]
struct Pins {
    uart_rx: u8,
    uart_tx: u8,
}

/// A parsed board ready for codegen.
struct Board {
    name: String,
    struct_name: String,
    feature: String,
    url: Option<String>,
    uart_rx: u8,
    uart_tx: u8,
}

/// Errors surfaced by the build script as `Result`.
#[derive(Debug)]
enum BuildError {
    /// A board feature was selected in Cargo.toml but no matching TOML file
    /// was found in `boards/`.
    MissingBoardDef { feature: String },
    /// A `boards/*.toml` file could not be read or parsed.
    BoardFile {
        path: PathBuf,
        source: Box<dyn std::error::Error>,
    },
}

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingBoardDef { feature } => write!(
                f,
                "Feature `{feature}` is enabled in Cargo.toml but no corresponding \
                 board definition file `boards/{feature}.toml` was found. \
                 Create it with a [pins] section containing uart_rx and uart_tx.",
            ),
            Self::BoardFile { path, source } => {
                write!(
                    f,
                    "Failed to process board file {}: {source}",
                    path.display()
                )
            }
        }
    }
}

impl std::error::Error for BuildError {}

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

fn main() -> Result<()> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let boards_dir = manifest_dir.join("boards");

    println!("cargo:rerun-if-changed=boards/");

    let boards = load_boards(&boards_dir)?;

    validate_features(&boards)?;

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set by cargo")?);
    let out_path = out_dir.join("boards_gen.rs");
    fs::write(&out_path, generate_code(&boards)?)?;

    Ok(())
}

/// Read all `boards/*.toml` files and parse them into `Board` structs.
fn load_boards(boards_dir: &Path) -> Result<Vec<Board>> {
    if !boards_dir.is_dir() {
        return Ok(Vec::new());
    }

    let mut entries: Vec<_> = fs::read_dir(boards_dir)?
        .filter_map(std::result::Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    entries.sort();

    let mut boards = Vec::new();
    for path in entries {
        let stem = path
            .file_stem()
            .ok_or("board file has no stem")?
            .to_string_lossy()
            .to_string();

        let content = fs::read_to_string(&path).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        let def: BoardDef = toml::from_str(&content).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        boards.push(Board {
            name: stem.clone(),
            struct_name: to_pascal_case(&stem),
            feature: format!("board-{stem}"),
            url: def.url,
            uart_rx: def.pins.uart_rx,
            uart_tx: def.pins.uart_tx,
        });
    }

    Ok(boards)
}

/// Check that every selected `CARGO_FEATURE_BOARD_*` env var has a matching
/// board TOML file.
fn validate_features(boards: &[Board]) -> Result<()> {
    for (key, _val) in std::env::vars() {
        if let Some(rest) = key.strip_prefix("CARGO_FEATURE_BOARD_") {
            let requested = format!("board-{}", rest.to_lowercase().replace('_', "-"));
            if boards.iter().any(|b| b.feature == requested) {
                continue;
            }
            return Err(BuildError::MissingBoardDef { feature: requested }.into());
        }
    }
    Ok(())
}

/// Convert `esp32c6-devkitc` -> `Esp32c6Devkitc`.
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn generate_code(boards: &[Board]) -> Result<String> {
    let mut out = String::new();

    out.push_str(HEADER);
    gen_structs(&mut out, boards)?;
    gen_catalog(&mut out, boards)?;
    gen_take_uart_pins(&mut out, boards);
    gen_select_board(&mut out, boards);

    Ok(out)
}

fn gen_structs(out: &mut String, boards: &[Board]) -> Result<()> {
    // One `pub struct` + `impl Board` per board, with a rustdoc link to the
    // board's official documentation page (if the TOML provided a `url`).
    for b in boards {
        let doc = match &b.url {
            Some(url) => format!("/// Board: {}.\n///\n/// <{url}>", b.name),
            None => format!("/// Board: {}.", b.name),
        };
        writeln!(
            out,
            "{doc}\npub struct {s};\nimpl Board for {s} {{\n    const NAME: &str = \"{n}\";\n}}",
            s = b.struct_name,
            n = b.name,
        )?;
        out.push('\n');
    }
    Ok(())
}

fn gen_catalog(out: &mut String, boards: &[Board]) -> Result<()> {
    // A rustdoc table summarising all boards — rendered in `cargo doc` output
    // as the `board_catalog` module page. This is the "one place to look" that
    // replaces the old hand-maintained README pin table.
    writeln!(
        out,
        "/// # Available boards\n///\n/// | Board feature | UART RX | UART TX | URL |\n/// |---|---|---|---|"
    )?;
    for b in boards {
        let url = match &b.url {
            Some(u) => format!("<{u}>"),
            None => "—".to_string(),
        };
        writeln!(
            out,
            "/// | `{}` | {} | {} | {} |",
            b.feature, b.uart_rx, b.uart_tx, url,
        )?;
    }
    writeln!(out, "pub mod board_catalog {{}}\n")?;
    Ok(())
}

/// Per-board `#[cfg]` branch inside `take_uart_pins!`.
///
/// Each branch expands to a tuple of `(AnyPin, AnyPin, u8, u8)` — the two GPIO
/// singletons consumed by the UART driver, plus the raw pin numbers persisted
/// in `SSHStampConfig`. The `GPIO{N}` field-access tokens are built here from
/// the TOML's pin numbers; they cannot be constructed at source level because
/// esp-hal's peripheral singletons are named fields (`peripherals.GPIO10`).
const UART_PIN_BRANCH: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            (
                $peripherals.GPIO{rx}.into(),
                $peripherals.GPIO{tx}.into(),
                {rx}u8,
                {tx}u8,
            )
        }}
"#;

fn gen_take_uart_pins(out: &mut String, boards: &[Board]) {
    // Build the per-board `#[cfg]` branches from the TOML pin data.
    let mut branches = String::new();
    for b in boards {
        branches.push_str(
            &UART_PIN_BRANCH
                .replace("{feature}", &b.feature)
                .replace("{rx}", &b.uart_rx.to_string())
                .replace("{tx}", &b.uart_tx.to_string()),
        );
    }

    // The fallback `not(any(...))` guard lists every board feature so that
    // selecting none produces a clear compile_error.
    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = TAKE_UART_PINS_TMPL
        .replace("{branches}", &branches)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
    out.push('\n');
}

/// One `#[cfg]`-guarded `type B` alias inside `select_board!`.
const SELECT_BOARD_ARM: &str = r#"        #[cfg(feature = "{feature}")]
        type B = $crate::{struct_name};
"#;

fn gen_select_board(out: &mut String, boards: &[Board]) {
    // Build the per-board `type B = ...` aliases. Each is guarded by its
    // `#[cfg(feature = ...)]` so only the active board's alias is compiled.
    let mut arms = String::new();
    for b in boards {
        arms.push_str(
            &SELECT_BOARD_ARM
                .replace("{feature}", &b.feature)
                .replace("{struct_name}", &b.struct_name),
        );
    }

    // The fallback `not(any(...))` guard produces a compile_error if no board
    // feature is selected.
    let features: Vec<String> = boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect();

    let rendered = SELECT_BOARD_TMPL
        .replace("{arms}", &arms)
        .replace("{features}", &features.join(", "));

    out.push_str(&rendered);
}
