# SPDX-FileCopyrightText: 2026 Julio Beltran Ortega <jubeormk1@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "ota"
version = "0.1.0"
edition = "2024"

[features]
default = []
packer = ["dep:clap"]
sftp = ["dep:sunset-sftp"]

[dependencies]
ssh-stamp-hal = { path = "../ssh-stamp-hal" }
sunset.workspace = true
sunset-async.workspace = true
sunset-sftp = { workspace = true, optional = true }

log.workspace = true
sha2.workspace = true

# Only for the packer binary
[target.'cfg(not(target_os = "none"))'.dependencies]
clap = { version = "4.5", optional = true }

[lints]
workspace = true

[[bin]]
name = "packer"
path = "src/bin/packer.rs"
required-features = ["packer"]
