# SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Waveshare ESP32-S3-Touch-LCD-4.3
url = "https://docs.waveshare.com/ESP32-S3-Touch-LCD-4.3"

[pins]
uart_rx = 44
uart_tx = 43
can_tx = 20
can_rx = 19
