# Map with the name of the serial device as found in /dev/serial/by-id/ folder and 
# the function (prog_*, com_*, other_*)
usb-1a86_USB_Single_Serial_5AE7080382-if00=prog_esp32s3
usb-FTDI_FT232R_USB_UART_AN94725E-if00-port0=com_esp32s2
usb-1a86_USB_Serial-if00-port0=prog_esp32
usb-FTDI_FT232R_USB_UART_A300V04K-if00-port0=com_esp32
usb-Espressif_USB_JTAG_serial_debug_unit_40:4C:CA:8C:E9:7C-if00=prog_esp32c3
usb-FTDI_FT232R_USB_UART_AV74K0PO-if00-port0=com_esp32c3
usb-Espressif_USB_JTAG_serial_debug_unit_F0:F5:BD:0E:60:58-if00=prog_esp32c6
usb-FTDI_FT232R_USB_UART_AT4P96AZ-if00-port0=com_esp32c6
