// SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Build script for ssh-stamp-rp2350-boards.
//!
//! Same contract as `ssh-stamp-esp32-boards`: read `boards/*.toml` (one file
//! per board) and generate `OUT_DIR/boards_gen.rs` with:
//!
//! - A `pub struct` + `impl Board` per board.
//! - The `take_uart_pins!` macro.
//! - The `take_ethernet_pins!` macro (boards with an `[ethernet]` section).
//! - The `select_board!` macro.
//! - A rustdoc board-catalog table.
//!
//! Adding a board = add a `boards/{name}.toml` file + a `board-{name}`
//! feature in `Cargo.toml`. No `.rs` file, no macro editing.
//!
//! Unlike the ESP32 BSP, the pin macros expand to the *concrete*
//! `peripherals.PIN_n` fields rather than erasing to `AnyPin`: embassy-rp
//! constrains UART pins with per-instance `TxPin`/`RxPin` traits that
//! `AnyPin` does not implement.

use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

// --- Static code templates ---

const HEADER: &str = "// Auto-generated by build.rs from boards/*.toml — DO NOT EDIT.\n\n";

const TAKE_UART_PINS_TMPL: &str = r#"/// Extract UART GPIO pins and logical pin numbers from `peripherals`.
///
/// Returns `(rx_pin, tx_pin, rx_num, tx_num)`. The pin numbers come from
/// `boards/*.toml` — this macro is generated by `build.rs`.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! take_uart_pins {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-rp2350-boards crate for available boards.");
        }}
    }};
}
"#;

/// Per-board branch of `take_uart_pins!`.
///
/// `PIN_{n}` field tokens are built here from the TOML pin numbers: they
/// cannot be written at source level because embassy-rp's peripheral
/// singletons are named struct fields.
const UART_PIN_BRANCH: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            (
                $peripherals.PIN_{rx},
                $peripherals.PIN_{tx},
                {rx}u8,
                {tx}u8,
            )
        }}
"#;

const TAKE_ETHERNET_PINS_TMPL: &str = r#"/// Extract the Ethernet controller's GPIO pins from `peripherals`.
///
/// Returns `(int, cs, sck, io0, io1, rst)`. Only call this macro on boards
/// whose TOML declares an `[ethernet]` section.
///
/// # Panics
///
/// Compile-time error if no board feature is selected, or if the selected
/// board has no Ethernet controller.
#[macro_export]
macro_rules! take_ethernet_pins {
    ($peripherals:expr) => {{
{branches}        #[cfg(not(any({features})))]
        {{
            compile_error!("No board feature selected. Pass --features board-<name>. See ssh-stamp-rp2350-boards crate for available boards.");
        }}
    }};
}
"#;

const ETHERNET_PIN_BRANCH_SOME: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            (
                $peripherals.PIN_{int},
                $peripherals.PIN_{cs},
                $peripherals.PIN_{sck},
                $peripherals.PIN_{io0},
                $peripherals.PIN_{io1},
                $peripherals.PIN_{rst},
            )
        }}
"#;

const ETHERNET_PIN_BRANCH_NONE: &str = r#"        #[cfg(feature = "{feature}")]
        {{
            compile_error!("Board `{feature}` has no [ethernet] section in its boards/*.toml, so it has no Ethernet pins to take.");
        }}
"#;

const SELECT_BOARD_TMPL: &str = r#"/// Select the active board type `B` at compile time.
///
/// Emits a `type B = ...` alias for the active board's struct, so the
/// caller can use `B::NAME` for logging with zero per-board lines.
///
/// # Panics
///
/// Compile-time error if no board feature is selected.
#[macro_export]
macro_rules! select_board {
    () => {
{arms}        #[cfg(not(any({features})))]
        compile_error!("No board feature selected.");
    };
}
"#;

const SELECT_BOARD_ARM: &str = r#"        #[cfg(feature = "{feature}")]
        type B = $crate::{struct_name};
"#;

// --- TOML deserialization ---

#[derive(Debug, Deserialize)]
struct BoardDef {
    url: Option<String>,
    pins: Pins,
    ethernet: Option<Ethernet>,
}

#[derive(Debug, Deserialize)]
struct Pins {
    uart_rx: u8,
    uart_tx: u8,
}

/// Onboard Ethernet controller wiring.
#[derive(Debug, Deserialize)]
struct Ethernet {
    chip: String,
    int: u8,
    cs: u8,
    sck: u8,
    io0: u8,
    io1: u8,
    rst: u8,
}

/// A parsed board ready for codegen.
struct Board {
    name: String,
    struct_name: String,
    feature: String,
    url: Option<String>,
    uart_rx: u8,
    uart_tx: u8,
    ethernet: Option<Ethernet>,
}

#[derive(Debug)]
enum BuildError {
    MissingBoardDef {
        feature: String,
    },
    BoardFile {
        path: PathBuf,
        source: Box<dyn std::error::Error>,
    },
}

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingBoardDef { feature } => write!(
                f,
                "Feature `{feature}` is enabled in Cargo.toml but no corresponding \
                 board definition file `boards/{feature}.toml` was found. \
                 Create it with a [pins] section containing uart_rx and uart_tx.",
            ),
            Self::BoardFile { path, source } => {
                write!(
                    f,
                    "Failed to process board file {}: {source}",
                    path.display()
                )
            }
        }
    }
}

impl std::error::Error for BuildError {}

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

fn main() -> Result<()> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let boards_dir = manifest_dir.join("boards");

    println!("cargo:rerun-if-changed=boards/");

    let boards = load_boards(&boards_dir)?;
    validate_features(&boards)?;

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set by cargo")?);
    fs::write(out_dir.join("boards_gen.rs"), generate_code(&boards)?)?;

    Ok(())
}

fn load_boards(boards_dir: &Path) -> Result<Vec<Board>> {
    if !boards_dir.is_dir() {
        return Ok(Vec::new());
    }

    let mut entries: Vec<_> = fs::read_dir(boards_dir)?
        .filter_map(std::result::Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
        .collect();
    entries.sort();

    let mut boards = Vec::new();
    for path in entries {
        let stem = path
            .file_stem()
            .ok_or("board file has no stem")?
            .to_string_lossy()
            .to_string();

        let content = fs::read_to_string(&path).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        let def: BoardDef = toml::from_str(&content).map_err(|e| BuildError::BoardFile {
            path: path.clone(),
            source: Box::new(e),
        })?;

        boards.push(Board {
            name: stem.clone(),
            struct_name: to_pascal_case(&stem),
            feature: format!("board-{stem}"),
            url: def.url,
            uart_rx: def.pins.uart_rx,
            uart_tx: def.pins.uart_tx,
            ethernet: def.ethernet,
        });
    }

    Ok(boards)
}

fn validate_features(boards: &[Board]) -> Result<()> {
    for (key, _val) in std::env::vars() {
        if let Some(rest) = key.strip_prefix("CARGO_FEATURE_BOARD_") {
            let requested = format!("board-{}", rest.to_lowercase().replace('_', "-"));
            if boards.iter().any(|b| b.feature == requested) {
                continue;
            }
            return Err(BuildError::MissingBoardDef { feature: requested }.into());
        }
    }
    Ok(())
}

/// Convert `w6300-evb-pico2` -> `W6300EvbPico2`.
fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .map(|segment| {
            let mut chars = segment.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn generate_code(boards: &[Board]) -> Result<String> {
    let mut out = String::new();

    out.push_str(HEADER);
    gen_structs(&mut out, boards)?;
    gen_catalog(&mut out, boards)?;
    gen_take_uart_pins(&mut out, boards);
    gen_take_ethernet_pins(&mut out, boards);
    gen_select_board(&mut out, boards);

    Ok(out)
}

fn gen_structs(out: &mut String, boards: &[Board]) -> Result<()> {
    for b in boards {
        let doc = match &b.url {
            Some(url) => format!("/// Board: {}.\n///\n/// <{url}>", b.name),
            None => format!("/// Board: {}.", b.name),
        };
        writeln!(
            out,
            "{doc}\npub struct {s};\nimpl Board for {s} {{\n    const NAME: &str = \"{n}\";\n}}",
            s = b.struct_name,
            n = b.name,
        )?;
        out.push('\n');
    }
    Ok(())
}

fn gen_catalog(out: &mut String, boards: &[Board]) -> Result<()> {
    writeln!(
        out,
        "/// # Available boards\n///\n/// | Board feature | UART RX | UART TX | Ethernet | URL |\n/// |---|---|---|---|---|"
    )?;
    for b in boards {
        let url = match &b.url {
            Some(u) => format!("<{u}>"),
            None => "—".to_string(),
        };
        let eth = b.ethernet.as_ref().map_or("—".to_string(), |e| {
            format!(
                "{} (int {}, cs {}, sck {}, io0 {}, io1 {}, rst {})",
                e.chip, e.int, e.cs, e.sck, e.io0, e.io1, e.rst
            )
        });
        writeln!(
            out,
            "/// | `{}` | {} | {} | {} | {} |",
            b.feature, b.uart_rx, b.uart_tx, eth, url,
        )?;
    }
    writeln!(out, "pub mod board_catalog {{}}\n")?;
    Ok(())
}

fn feature_list(boards: &[Board]) -> String {
    boards
        .iter()
        .map(|b| format!("feature = \"{}\"", b.feature))
        .collect::<Vec<_>>()
        .join(", ")
}

fn gen_take_uart_pins(out: &mut String, boards: &[Board]) {
    let mut branches = String::new();
    for b in boards {
        branches.push_str(
            &UART_PIN_BRANCH
                .replace("{feature}", &b.feature)
                .replace("{rx}", &b.uart_rx.to_string())
                .replace("{tx}", &b.uart_tx.to_string()),
        );
    }

    out.push_str(
        &TAKE_UART_PINS_TMPL
            .replace("{branches}", &branches)
            .replace("{features}", &feature_list(boards)),
    );
    out.push('\n');
}

fn gen_take_ethernet_pins(out: &mut String, boards: &[Board]) {
    let mut branches = String::new();
    for b in boards {
        if let Some(e) = &b.ethernet {
            branches.push_str(
                &ETHERNET_PIN_BRANCH_SOME
                    .replace("{feature}", &b.feature)
                    .replace("{int}", &e.int.to_string())
                    .replace("{cs}", &e.cs.to_string())
                    .replace("{sck}", &e.sck.to_string())
                    .replace("{io0}", &e.io0.to_string())
                    .replace("{io1}", &e.io1.to_string())
                    .replace("{rst}", &e.rst.to_string()),
            );
        } else {
            branches.push_str(&ETHERNET_PIN_BRANCH_NONE.replace("{feature}", &b.feature));
        }
    }

    out.push_str(
        &TAKE_ETHERNET_PINS_TMPL
            .replace("{branches}", &branches)
            .replace("{features}", &feature_list(boards)),
    );
    out.push('\n');
}

fn gen_select_board(out: &mut String, boards: &[Board]) {
    let mut arms = String::new();
    for b in boards {
        arms.push_str(
            &SELECT_BOARD_ARM
                .replace("{feature}", &b.feature)
                .replace("{struct_name}", &b.struct_name),
        );
    }

    out.push_str(
        &SELECT_BOARD_TMPL
            .replace("{arms}", &arms)
            .replace("{features}", &feature_list(boards)),
    );
}
