# SPDX-FileCopyrightText: 2026 Roman Valls Guimera <brainstorm@nopcode.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  espressif-targets:
    name: Espressif target ${{ matrix.device.soc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device: [
            # RISC-V devices:
            { soc: "esp32c2", toolchain: "stable" },
            { soc: "esp32c3", toolchain: "stable" },
#            { soc: "esp32c5", toolchain: "stable" },
            { soc: "esp32c6", toolchain: "stable" },
            # Xtensa devices:
            { soc: "esp32", toolchain: "esp" },
            { soc: "esp32s2", toolchain: "esp" },
            { soc: "esp32s3", toolchain: "esp" },
        ]
    steps:
      - name: Cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Rust toolchain for RISC-V
        if: ${{ !contains(fromJson('["esp32", "esp32s2", "esp32s3"]'), matrix.device.soc) }}
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf
          toolchain: stable
          components: rust-src, clippy, rustfmt
      - name: Setup Rust toolchain for Xtensa
        if: ${{ contains(fromJson('["esp32", "esp32s2", "esp32s3"]'), matrix.device.soc) }}
        uses: esp-rs/xtensa-toolchain@v1.7.0
        with:
          ldproxy: false
          version: 1.96.0

      - name: Build project
        run: cargo +${{ matrix.device.toolchain }} build-${{ matrix.device.soc }}

      - name: Check lints and format
        if: ${{ contains(fromJson('["esp32c6"]'), matrix.device.soc) }}
        run: |
          cargo +${{ matrix.device.toolchain }} clippy --release --features ${{ matrix.device.soc }} --target riscv32imac-unknown-none-elf -p ssh-stamp-esp32 --bin ssh-stamp-esp32 --no-default-features -- -D warnings -A clippy::default_trait_access
          cargo +${{ matrix.device.toolchain }} fmt -- --check
  packer:
    name: OTA Packer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imac-unknown-none-elf
          toolchain: stable
      - name: Build utility
        run: cargo build-packer
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imac-unknown-none-elf
          toolchain: stable
      - name: Build all docs
        run: cargo build-doc
      - name: Check doc warnings
        run: cargo build-doc 2>&1 | grep -iE "broken|warning.*link" || true
